"""Markdown rendering: verdict dict -> FactBot fact-check report.

Supports multiple languages via _I18N dict. The 'language' field from the
verdict dict (ISO 639-1 code, e.g. 'id', 'en', 'ja') selects the i18n set.
Unknown language codes fall back to English.
"""

import logging

logger = logging.getLogger(__name__)

# ── i18n dictionaries ────────────────────────────────────────────────────────

_I18N: dict[str, dict] = {
    "id": {
        "h1_prefix": "Hasil Analisa",
        "conclusion_label": "Kesimpulan",
        "sec_claim": "Klaim yang Dianalisa",
        "sec_evidence": "Bukti",
        "sec_kvf": "Klaim vs Fakta",
        "sec_sources": "Sumber Rujukan",
        "sec_notes": "Catatan",
        "ctx_label": "Konteks (caption/title)",
        "cat_label": "Kategori",
        "conf_label": "Tingkat keyakinan",
        "col_claim": "Klaim",
        "col_fact": "Fakta",
        "no_evidence": "Belum ada bukti yang cukup untuk memverifikasi klaim ini.",
        "no_sources": "Belum ada sumber rujukan.",
        "no_notes": "Tidak ada catatan tambahan.",
        "unverified_cell": "Belum dapat diverifikasi",
        "disclaimer": (
            "Dokumen ini dihasilkan otomatis oleh FactBot. "
            "Selalu cek sumber resmi sebelum menyebarkan informasi."
        ),
        "verdicts": {
            "fact": "✅ FAKTA",
            "hoax": "❌ HOAX",
            "partly_true": "⚠️ SEBAGIAN BENAR",
            "unverified": "❔ BELUM DAPAT DIVERIFIKASI",
        },
    },
    "en": {
        "h1_prefix": "Analysis Result",
        "conclusion_label": "Conclusion",
        "sec_claim": "Claim Under Review",
        "sec_evidence": "Evidence",
        "sec_kvf": "Claim vs Fact",
        "sec_sources": "References",
        "sec_notes": "Notes",
        "ctx_label": "Context (caption/title)",
        "cat_label": "Category",
        "conf_label": "Confidence level",
        "col_claim": "Claim",
        "col_fact": "Fact",
        "no_evidence": "Not enough evidence to verify this claim.",
        "no_sources": "No references available.",
        "no_notes": "No additional notes.",
        "unverified_cell": "Could not be verified",
        "disclaimer": (
            "This document was automatically generated by FactBot. "
            "Always check official sources before sharing information."
        ),
        "verdicts": {
            "fact": "✅ FACT",
            "hoax": "❌ HOAX",
            "partly_true": "⚠️ PARTLY TRUE",
            "unverified": "❔ UNVERIFIED",
        },
    },
    "ja": {
        "h1_prefix": "分析結果",
        "conclusion_label": "結論",
        "sec_claim": "検証対象の主張",
        "sec_evidence": "証拠",
        "sec_kvf": "主張 vs 事実",
        "sec_sources": "参考文献",
        "sec_notes": "注記",
        "ctx_label": "文脈（キャプション）",
        "cat_label": "カテゴリ",
        "conf_label": "信頼度",
        "col_claim": "主張",
        "col_fact": "事実",
        "no_evidence": "この主張を検証するのに十分な証拠がありません。",
        "no_sources": "参考文献はありません。",
        "no_notes": "追加のメモはありません。",
        "unverified_cell": "検証できませんでした",
        "disclaimer": (
            "このドキュメントはFactBotによって自動生成されました。"
            "情報を共有する前に公式ソースを確認してください。"
        ),
        "verdicts": {
            "fact": "✅ 事実",
            "hoax": "❌ 虚偽",
            "partly_true": "⚠️ 一部事実",
            "unverified": "❔ 未確認",
        },
    },
    "ar": {
        "h1_prefix": "نتيجة التحليل",
        "conclusion_label": "الخلاصة",
        "sec_claim": "الادعاء قيد المراجعة",
        "sec_evidence": "الأدلة",
        "sec_kvf": "الادعاء مقابل الحقيقة",
        "sec_sources": "المراجع",
        "sec_notes": "ملاحظات",
        "ctx_label": "السياق (التعليق/العنوان)",
        "cat_label": "الفئة",
        "conf_label": "مستوى الثقة",
        "col_claim": "الادعاء",
        "col_fact": "الحقيقة",
        "no_evidence": "لا توجد أدلة كافية للتحقق من هذا الادعاء.",
        "no_sources": "لا توجد مراجع متاحة.",
        "no_notes": "لا توجد ملاحظات إضافية.",
        "unverified_cell": "لم يمكن التحقق",
        "disclaimer": (
            "تم إنشاء هذا المستند تلقائيًا بواسطة FactBot. "
            "تحقق دائمًا من المصادر الرسمية قبل مشاركة المعلومات."
        ),
        "verdicts": {
            "fact": "✅ حقيقة",
            "hoax": "❌ زيف",
            "partly_true": "⚠️ صحيح جزئيًا",
            "unverified": "❔ غير محقق",
        },
    },
    "es": {
        "h1_prefix": "Resultado del Análisis",
        "conclusion_label": "Conclusión",
        "sec_claim": "Afirmación bajo revisión",
        "sec_evidence": "Evidencia",
        "sec_kvf": "Afirmación vs Hecho",
        "sec_sources": "Referencias",
        "sec_notes": "Notas",
        "ctx_label": "Contexto (pie de foto/título)",
        "cat_label": "Categoría",
        "conf_label": "Nivel de confianza",
        "col_claim": "Afirmación",
        "col_fact": "Hecho",
        "no_evidence": "No hay suficiente evidencia para verificar esta afirmación.",
        "no_sources": "No hay referencias disponibles.",
        "no_notes": "No hay notas adicionales.",
        "unverified_cell": "No se pudo verificar",
        "disclaimer": (
            "Este documento fue generado automáticamente por FactBot. "
            "Siempre verifique fuentes oficiales antes de compartir información."
        ),
        "verdicts": {
            "fact": "✅ HECHO",
            "hoax": "❌ ENGAÑO",
            "partly_true": "⚠️ PARCIALMENTE VERDADERO",
            "unverified": "❔ SIN VERIFICAR",
        },
    },
}

_I18N_FALLBACK = "en"

CATEGORY_LABELS = {
    "health": "Health / Kesehatan",
    "government": "Government / Pemerintahan",
    "politics": "Politics / Politik",
    "disaster": "Disaster / Bencana",
    "finance": "Finance / Keuangan",
    "technology": "Technology / Teknologi",
    "religion": "Religion / Agama",
    "education": "Education / Pendidikan",
    "other": "Other / Lainnya",
}


def _get_i18n(lang: str) -> dict:
    """Return i18n dict for lang code. Falls back to English for unknown codes."""
    return _I18N.get((lang or "id")[:2].lower(), _I18N[_I18N_FALLBACK])


def _table_cell(text: str) -> str:
    """Sanitize text for markdown table cells (pipes & newlines)."""
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def _quote(text: str) -> str:
    """Wrap text as markdown blockquote."""
    if not text:
        return "> —"
    return "\n".join(f"> {line}" for line in str(text).splitlines())


async def render_markdown(verdict: dict) -> str:
    """Render a validated verdict dict into a complete multilingual markdown report."""
    lang = (verdict.get("language") or "id")[:2].lower()
    i18n = _get_i18n(lang)

    verdict_value = verdict.get("verdict", "unverified")
    label = i18n["verdicts"].get(verdict_value, i18n["verdicts"]["unverified"])

    category = CATEGORY_LABELS.get(verdict.get("category", "other"), "Other / Lainnya")
    claim = (verdict.get("claim") or "").strip() or "(claim not available)"
    context = (verdict.get("context") or "").strip()
    summary = (verdict.get("summary") or "").strip() or "No summary available."

    try:
        confidence_pct = f"{max(0.0, min(1.0, float(verdict.get('confidence', 0.0)))) * 100:.0f}%"
    except (TypeError, ValueError):
        confidence_pct = "—"

    evidence = [str(e).strip() for e in (verdict.get("evidence") or []) if str(e).strip()]
    sources = [str(s).strip() for s in (verdict.get("sources") or []) if str(s).strip()]
    notes = [str(n).strip() for n in (verdict.get("notes") or []) if str(n).strip()]

    # Title: prefer LLM-generated; fallback to claim snippet
    h1_title = (verdict.get("title") or "").strip()
    if not h1_title:
        h1_title = claim if len(claim) <= 80 else claim[:77] + "..."

    lines = [
        f"# {i18n['h1_prefix']}: {h1_title}",
        "",
        f"> **{i18n['conclusion_label']}: {label}** — {summary}",
        "",
        "---",
        "",
        f"## {i18n['sec_claim']}",
        "",
        _quote(claim),
        "",
    ]
    if context:
        lines.append(f"- **{i18n['ctx_label']}:** {_table_cell(context)}")
    lines += [
        f"- **{i18n['cat_label']}:** {category}",
        f"- **{i18n['conf_label']}:** {confidence_pct}",
        "",
        f"## {i18n['sec_evidence']}",
        "",
    ]
    if evidence:
        lines += [f"- {item}" for item in evidence]
    else:
        lines.append(f"- {i18n['no_evidence']}")
    lines += [
        "",
        f"## {i18n['sec_kvf']}",
        "",
        f"| {i18n['col_claim']} | {i18n['col_fact']} | Status |",
        "|---|---|---|",
    ]
    if evidence:
        lines += [f"| {_table_cell(claim)} | {_table_cell(item)} | {label} |" for item in evidence]
    else:
        lines.append(f"| {_table_cell(claim)} | {i18n['unverified_cell']} | {label} |")
    lines += [
        "",
        f"## {i18n['sec_sources']}",
        "",
    ]
    if sources:
        lines += [f"{i}. {src}" for i, src in enumerate(sources, 1)]
    else:
        lines.append(f"- {i18n['no_sources']}")
    lines += [
        "",
        f"## {i18n['sec_notes']}",
        "",
    ]
    if notes:
        lines += [f"- {note}" for note in notes]
    else:
        lines.append(f"- {i18n['no_notes']}")
    lines += [
        "",
        "---",
        "",
        f"*{i18n['disclaimer']}*",
        "",
    ]

    return "\n".join(lines)
